### ISSUE TITLE
Is it possible to create data without a wrds account?

### ISSUE THREAD

**Issue by jverkoey** [euclidjda/deep-quant#15]
I found that the `.dat` file fetched by `scripts/build_datfile.py` does not appear to contain all of the necessary columns (`saleq_ttm` for example). Unfortunately, I do not have a wrds account.

Would it be possible to provide an example .dat file that contains the needed columns and example values?

**Comment by euclidjda** [comment]
I just pushed an update to system-test.conf so that it works with the new open-dataset.dat headers. sales_ttm is there ... its is just been re-named REVENUE_TTM. Anyway, it should work now if you do a git pull. NOTE, though, that open-dataset.dat is just for testing the code. It has issues such as survivorship bias and lookahead bias. Unfortunately to get data without those biases an academic (WRDS) or commercial (cap iq) license is required.

**Comment by jverkoey** [comment]
Latest commit works - thank you!
